# Generated by Django 4.2.5 on 2023-09-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='user_id',
            field=models.IntegerField(default='11111', unique=True, verbose_name='User ID'),
        ),
    ]
