# Generated by Django 4.2.5 on 2023-09-16 06:15

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customusers_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='user_id',
            field=models.IntegerField(default=users.models.generate_unique_user_id, unique=True, verbose_name='User ID'),
        ),
    ]
