# Generated by Django 4.2.5 on 2023-09-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customusers_mobile_alter_customusers_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='image',
            field=models.ImageField(blank=True, default='default_images/user.png', null=True, upload_to='Users/%Y/%m/'),
        ),
    ]
