# Generated by Django 4.2.5 on 2023-09-16 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customusers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Birinchi ro'yxatdan o'tilgan vaqt"),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='image',
            field=models.ImageField(blank=True, default='default_images/user.png', null=True, upload_to='Users/%Y/%m/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='SuperAdmin'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tizimga kirgan vaqt'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
    ]
