# Generated by Django 4.2.5 on 2023-09-16 10:37

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customusers_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='user_id',
            field=models.IntegerField(default=users.models.generate_unique_user_id, editable=False, unique=True, verbose_name='User ID'),
        ),
    ]
