# Generated by Django 4.2.5 on 2023-09-16 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_alter_daynumber_options_alter_daynumber_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='Spelling - Aytilishi')),
                ('transcription', models.CharField(blank=True, max_length=200, null=True, verbose_name="Pronunciation - O'qilishi")),
                ('translation', models.CharField(max_length=300, verbose_name='Translation - Tarjimasi')),
                ('image', models.ImageField(upload_to='Words/%Y/%m', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.daynumber')),
            ],
        ),
    ]
