# Generated by Django 4.2.5 on 2023-09-16 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0003_words'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='words',
            options={'verbose_name': "So'zlar", 'verbose_name_plural': "So'zlar"},
        ),
        migrations.AddField(
            model_name='words',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='words',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Words/%Y/%m', verbose_name='Rasm'),
        ),
    ]
