# Generated by Django 4.2.5 on 2023-09-16 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('words', '0004_alter_words_options_words_user_alter_words_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='words.daynumber'),
        ),
        migrations.AlterField(
            model_name='words',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
