# Generated by Django 4.2.5 on 2023-09-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_alter_words_day_alter_words_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nomi')),
                ('view_home', models.BooleanField(default=False, verbose_name='Faollik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
            ],
            options={
                'verbose_name': "So'zning qiyinlik darajasi",
                'verbose_name_plural': "So'zning qiyinlik darajasi",
                'ordering': ('-created_at', 'updated_at'),
            },
        ),
    ]
